# Generated by Django 3.2 on 2021-04-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Tenatative_Return_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='require_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
